platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((app-broker-dev-docker-registry))/ci/app-broker-ci
    username: ((broadcom-jfrog-artifactory-robot-account.username))
    password: ((broadcom-jfrog-artifactory-robot-account.password))
    tag: ((ci-image-tag))

inputs:
  - name: git-repo

outputs:
  - name: prs

run:
  path: bash
  dir: git-repo
  args:
    - -c
    - |
      gh pr list --state open --search "review:approved"
      gh pr list --state open --search "review:approved" --json number,baseRefName,headRefOid,author > ../prs/prs.json

params:
  GH_TOKEN: ((app-broker-pr-github-pull-requests-access-token))
